- name: Shibboleth SP | Suomi.fi | clean |
  xml:
    xpath: "{{ shibsp_item }}"
    state: "absent"
    file: "/etc/shibboleth/shibboleth2.xml"
    namespaces:
      x: urn:mace:shibboleth:3.0:native:sp:config
  loop_control:
    loop_var: shibsp_item
  with_items:
    - '/x:SPConfig/x:ApplicationDefaults/x:RelyingParty[@Name="https://uusi.tunnistus.fi/idp1"]'
    - '/x:SPConfig/x:ApplicationDefaults/x:RelyingParty[@Name="https://tunnistautuminen.suomi.fi/idp1"]'
    - '/x:SPConfig/x:ApplicationDefaults/x:MetadataProvider[@url="{{ shibbolethsp_suomifimd }}"]'
    - '/x:SPConfig/x:ApplicationDefaults/x:CredentialResolver[@type="Chaining"]/x:CredentialResolver[@keyName="suomifi-cert"]'

- name: Shibboleth SP | Suomi.fi | Metadata | Configure
  xml:
    file: "/etc/shibboleth/shibboleth2.xml"
    xpath: "//x:SPConfig/x:ApplicationDefaults/x:Errors"
    insertafter: yes
    pretty_print: yes
    namespaces:
      x: urn:mace:shibboleth:3.0:native:sp:config
    add_children:
      - MetadataProvider:
          type: "XML"
          url: "{{ shibbolethsp_suomifimd }}"
          backingFilePath: "suomifi-metadata.xml"
          reloadInterval: "3600"

- name: Shibboleth SP | Suomi.fi | RelyingParty | Configure
  xml:
    file: "/etc/shibboleth/shibboleth2.xml"
    xpath: "//x:SPConfig/x:ApplicationDefaults/x:AttributeFilter"
    insertafter: yes
    pretty_print: yes
    namespaces:
      x: urn:mace:shibboleth:3.0:native:sp:config
    add_children:
      - RelyingParty:
          Name: "https://uusi.tunnistus.fi/idp1"
          keyName: "suomifi-cert"
      - RelyingParty:
          Name: "https://tunnistautuminen.suomi.fi/idp1"
          keyName: "suomifi-cert"
   
- name: Shibboleth SP | Suomi.fi | Credentials | Configure |
  xml:
    file: "/etc/shibboleth/shibboleth2.xml"
    xpath: "//x:SPConfig/x:ApplicationDefaults/x:CredentialResolver[@type='Chaining']"
    pretty_print: yes
    namespaces:
      x: urn:mace:shibboleth:3.0:native:sp:config
    add_children:
      - CredentialResolver:
          type: "File"
          key: "/etc/pki/tls/private/{{ shibbolethsp_fqdn }}.saml.suomifi.key"
          certificate: "/etc/pki/tls/certs/{{ shibbolethsp_fqdn }}.saml.suomifi.crt"
          keyName: "suomifi-cert"

