- name: Shibboleth SP | Metadata | Haka-test | Download | Certificate
  get_url: url={{ shibbolethsp_hakatestcrt }} dest=/etc/pki/tls/certs/{{ shibbolethsp_hakatestcrt | basename }} mode=0755

- name: Shibboleth SP | Haka-test | clean |
  xml:
    xpath: "{{ shibsp_item }}"
    state: "absent"
    file: "/etc/shibboleth/shibboleth2.xml"
    namespaces:
      x: urn:mace:shibboleth:3.0:native:sp:config
  loop_control:
    loop_var: shibsp_item
  with_items:
    - '/x:SPConfig/x:ApplicationDefaults/x:MetadataProvider[@url="{{ shibbolethsp_hakatestmd }}"]'

- name: Shibboleth SP | Haka-test | Metadata | Configure
  xml:
    file: "/etc/shibboleth/shibboleth2.xml"
    xpath: "//x:SPConfig/x:ApplicationDefaults/x:Errors"
    insertafter: yes
    pretty_print: yes
    namespaces:
      x: urn:mace:shibboleth:3.0:native:sp:config
    add_children:
      - MetadataProvider:
          type: "XML"
          url: "{{ shibbolethsp_hakatestmd }}"
          backingFilePath: "{{ shibbolethsp_hakatestmd | basename }}"
          reloadInterval: "3600"
          _:
             - MetadataFilter:
                 type: "Signature"
                 certificate: "/etc/pki/tls/certs/{{ shibbolethsp_hakatestcrt | basename }}"
             - MetadataFilter:
                 type: "RequireValidUntil"
                 maxValidityInterval: "2592000"

